Feature/application monitoring
philippabele/pythonic-api-design pull request #23
Opened 2022-05-23 14:23 UTC by HenrikFrtz

I've added Prometheus for FastAPI. There are two new Docker Container: Prometheus and Grafana.
Grafana is the Frontend tool to show Prometheus monitoring data.

2022-05-24 13:54 UTC, philippabele requested changes
There are 1 failing and 3 cancelled checks.

Please sovle this issue first.

2022-05-24 20:39 UTC, HenrikFrtz commented
@philippabele 
Solved this issue. FYI: I changed pytest.yaml to build the Docker containers now. Pytest is now executed in the microservice container. 

If this is alright, I'm going to implement this in the other PR as well.

2022-05-25 18:56 UTC, philippabele requested changes
The idea of the project is to become a resource for future Python developer. Therefore it is necessary to group your API examples into sub directories.

Please create a working sub directory for each example of a fastAPI app. Do not put all your work into one holistic model. Keep your examples modular, to make cherry picking possible.

Think of your other pending PRs as well. There should be a clear and simple tree like structure to get a fast overview of your examples.

./root
| - ./01_simple_crud_sql
| - ./02_simple_elastic_logging
| - ./03_grafana_monitoring

2022-05-27 14:44 UTC, philippabele approved these changes

2022-05-28 10:10 UTC, merged